Add python client for FM API
dataiku/dataiku-api-client-python pull request #153
Opened 2021-06-03 10:51 UTC by thibaudio

2021-09-21 19:50 UTC, thibaudio commented
I've updated the PR, but left the snapshots and getting the default vpc/subnet when creating networks out of the scope because the public api is lacking for now.

2021-09-22 14:12 UTC, FChataigner requested changes
- not too fond of the methods `set_...()` that do a `save()` internally. I'd rather have the method return `self` so that you can chain a `save()` if you want
- no way to guess the image id for creation

2021-09-22 14:12 UTC, FChataigner commented on dataikuapi/fm/instancesettingstemplates.py
> +    def with_license(self, license):
missing docstring

2021-09-23 10:57 UTC, thibaudio commented on dataikuapi/fmclient.py
> +        self.__tenant_id = tenant_id
An old habit, `__` for private variables vs `_` for protected variables.
I can update it to a single underscore if you prefer to

2021-09-28 08:09 UTC, FChataigner approved these changes
LGTM

2021-09-28 09:03 UTC, duckie approved these changes

2021-09-28 10:09 UTC, merged