Chore/dss10 clarify get variable apis
dataiku/dataiku-api-client-python pull request #161
Opened 2021-08-12 12:29 UTC by AFrancani

Clarify the `get_*variables` apis:
- rename `dataikuapi.dssclient.DSSClient.get_variables` to `dataikuapi.dssclient.DSSClient.get_global_variables` to clarify its intention
- recreate `dataikuapi.dssclient.DSSClient.get_variables` as a proxy to `dataikuapi.dssclient.DSSClient.get_global_variables` and deprecate it to inform users they should use the new method
- add `dataikuapi.dssclient.DSSClient.get_resolved_variables` mimicing `dataiku.get_custom_variables` to get access to resolved variables without admin permissions

2021-08-16 15:35 UTC, marchelleboid requested changes

2021-08-16 15:35 UTC, marchelleboid commented on dataikuapi/dss/admin.py
> +        super().__init__()
This syntax doesn't seem to work in python 2.7. I think we still want to support python 2.7, so you'll probably need to stick with `super(dict, self).__init__()` (I think that still works in python 3)

2021-08-16 15:35 UTC, marchelleboid commented on dataikuapi/dssclient.py
> +    def get_resolved_variables(self, project_key=None, typed=False):
Even though the CH mentions `DSSClient.get_resolved_variables()`, I think this belongs in `DSSProject`, alongside the existing `DSSProject.get_variables()`.

2021-08-17 09:16 UTC, qcastel commented on dataikuapi/dssclient.py
>              "PUT", "/admin/variables/", body=variables)
Should we not try to use `get_global_variables().save()` instead?

2021-08-17 09:19 UTC, qcastel commented on dataikuapi/dss/project.py
> +        :return: a dictionary with instance and project variables merged
I guess this line is not needed

2021-08-17 10:21 UTC, qcastel approved these changes

2021-08-17 10:23 UTC, marchelleboid approved these changes

2021-08-17 10:31 UTC, marchelleboid commented on dataikuapi/dss/admin.py
> +    Do not create this directly, use :meth:`dataikuapi.dssclient.DSSClient.get_global_variables`
While checking the doc PR, I noticed that this method link needs to be `dataikuapi.DSSClient.get_global_variables`

2021-08-17 10:34 UTC, marchelleboid commented on dataikuapi/dssclient.py
> +        Deprecated. Use get_global_variables
Should we add a method link to the new method for the doc (even if it's right next to it)? Same with deprecated comment in `set_variables`

2021-11-21 18:30 UTC, mhoarau requested changes

2021-12-17 08:25 UTC, merged