Feature/dss10 api evaluate recipe creation
dataiku/dataiku-api-client-python pull request #162
Opened 2021-08-12 16:30 UTC by vthorey

[[ch58502]](https://app.clubhouse.io/dataiku/story/58502/python-api-client-for-evaluate-recipe-creation)

- Add Evaluation recipe Creator

2021-08-13 11:26 UTC, lpenet requested changes
Some little changes to make

2021-08-13 11:26 UTC, lpenet commented on dataikuapi/dss/recipe.py
> +    Outputs can be created with
I would be more assertive. Something like:
"Outputs must exists. You can create them with"

2021-08-13 11:26 UTC, lpenet commented on dataikuapi/dss/recipe.py
> +        SingleOutputRecipeCreator.__init__(self, 'evaluation', name, project)
`SingleOutputRecipeCreator` => `DSSRecipeCreator`

2021-08-13 11:26 UTC, lpenet commented on dataikuapi/dss/recipe.py
> +        return self._with_output(name, role="evalutationStore")
Typo: `evalutationStore` => `evaluationStore`.

2021-08-13 12:41 UTC, vthorey commented on dataikuapi/dss/recipe.py
> +        return self._with_output(name, role="evalutationStore")
🤦

2021-09-01 13:14 UTC, FChataigner requested changes

2021-09-01 13:14 UTC, FChataigner commented on dataikuapi/dss/recipe.py
> +    def with_ouput(self, name):
typo "with_ouput" -> "with_output"

2021-09-01 13:20 UTC, vthorey commented on dataikuapi/dss/recipe.py
> +    def with_ouput(self, name):
🤦 that's fixed

2021-09-03 14:26 UTC, lpenet commented
LGTM! Will validate it when backend part is fully implemented and tested.

2021-09-09 11:31 UTC, lpenet commented
@instanceofme does not really add new entries to the API, rather extend existing ones. But nonetheless requesting your insight.

2021-09-09 13:21 UTC, instanceofme commented on dataikuapi/dss/recipe.py
> +        """Sets the output dataset containing the metrics"""
```suggestion
        """Sets the output model evaluation store"""
```

2021-09-09 13:21 UTC, instanceofme commented on dataikuapi/dss/recipe.py
> -class DownloadRecipeCreator(SingleOutputRecipeCreator):
Duplication to be handled in separate PR, see CH70141

2021-09-09 17:07 UTC, instanceofme approved these changes

2021-09-10 07:22 UTC, merged