[sc-68952] Add items to zone by batch
dataiku/dataiku-api-client-python pull request #195
Opened 2021-12-03 12:58 UTC by qcastel

This PR goes to pair with https://github.com/dataiku/dip/pull/14461

2021-12-03 12:58 UTC, qcastel commented
[sc-68952]

2021-12-06 12:10 UTC, marchelleboid requested changes

2021-12-06 12:10 UTC, marchelleboid commented on dataikuapi/dss/flow.py
> +                           or :class:`dataikuapi.dss.savedmodel.DSSSavedModel` to add to the zone
A few things here should be updated now that it's a list of items, probably operation -> operations, that phrase about the recipe, and the param description should be updated to say "a list of ..."

2021-12-07 13:48 UTC, marchelleboid approved these changes
LGTM with a couple final doc changes

2021-12-08 08:39 UTC, nikopol approved these changes
LGTM. You should add an exemple in [dss doc](https://doc.dataiku.com/dss/latest/python-api/flow.html#creating-a-zone-and-adding-items-in-it) too I guess.

2021-12-15 09:27 UTC, mhoarau requested changes

2021-12-17 12:57 UTC, qcastel commented on dataikuapi/dss/flow.py
> +        :param list items: A list of objects, either :class:`dataikuapi.dss.dataset.DSSDataset`, :class:`dataikuapi.dss.managedfolder.DSSManagedFolder`,
If you look at the same feature in the UI, you can't move recipe directly. However a recipe will be moved to the zone if the output dataset is moved to the zone. At least thats what I experienced in the UI so far

2021-12-30 09:43 UTC, mhoarau approved these changes

2022-01-10 08:19 UTC, merged