Allow sending a bearer token
dataiku/dataiku-api-client-python pull request #215
Opened 2022-02-16 09:36 UTC by qcastel

Allowing to send a bearer token, so we can give a python sample code

2022-02-18 08:17 UTC, qcastel commented
[sc-72323]

2022-02-18 17:32 UTC, thtrunck commented on dataikuapi/base_client.py
> +    def __init__(self, base_uri, api_key=None, bearer_token=None, internal_ticket=None):
Isn't that risky to add a new parameter in the middle of the signature?

2022-02-24 09:19 UTC, AFrancani requested changes
I agree with Theo's comment, apart from that LGTM

2022-03-04 14:14 UTC, AFrancani approved these changes

2022-03-08 09:48 UTC, thtrunck approved these changes

2022-04-27 13:56 UTC, merged