[SC-93184]: Refactor python client api for project libraries
dataiku/dataiku-api-client-python pull request #248
Opened 2022-07-25 16:51 UTC by ehysi

2022-08-31 16:12 UTC, MayeulRousselet requested changes
Thanks for this good work Erin, I have developped in the review some of my interrogations.

2022-08-31 16:12 UTC, MayeulRousselet commented on dataikuapi/dss/projectlibrary.py
> +class DSSLibraryFile(DSSLibraryItem):
Maybe we could store the content of the file in a prop, `content`
get_content()  -> do the call to get the file contents and update `content`
set_content() -> overwrite `content`
save() -> do the POST request to save the file 

WDYT?

2022-08-31 16:12 UTC, MayeulRousselet commented on dataikuapi/dss/projectlibrary.py
> +    def __init__(self, client, project_key):
I am not a fan of calling `reload` in the constructor.
For what I know, but I am not the biggest expert on the matter (You should ask guidance to Clement), usually in the client, the constructor will just init the handle, and do not perform any call. A subsequent call to `get_settings` will do it. cf what is done for the wiki.

2022-09-09 14:25 UTC, MayeulRousselet requested changes

2022-09-09 14:25 UTC, MayeulRousselet commented on dataikuapi/dss/projectlibrary.py
> +        Note : It is still not saved in DSS.
Precise: it is not saved in DSS until `contents(...)` is called

2022-09-19 09:21 UTC, MayeulRousselet approved these changes
LGTM

2022-09-22 16:36 UTC, apichery commented
Replaced by https://github.com/dataiku/dip/pull/18089

2022-09-22 16:36 UTC, closed without merging