Add time series forecasting capabilities
dataiku/dataiku-api-client-python pull request #260
Opened 2022-08-26 11:59 UTC by mhham

- Time series forecasting ML task
  - Creation
  - Core settings
  - Algorithms and hyperparameters
  - Guessing

- API node
  - Endpoint creation
  - Endpoint calling

SC-79580

2022-08-26 17:47 UTC, instanceofme reviewed
First, partial review of the small bits. Missing the bigger piece in `ml.py`

2022-08-26 17:47 UTC, instanceofme commented on dataikuapi/dss/dataset.py
> +    def create_timeseries_forecasting_ml_task(self, target_variable,
Ditto

2022-08-26 17:47 UTC, instanceofme commented on dataikuapi/dss/dataset.py
> +        :param list timeseries_identifiers:  List of columns to be used as time series identifiers
Same remarks as matching arguments in project handle

2022-08-26 17:47 UTC, instanceofme commented on dataikuapi/dss/ml.py
> +            raise Exception("Explicit splitting is only available for regression, binary, and multiple classification")
Are we sure? (Causal, deep hub…)

2022-08-31 16:23 UTC, instanceofme requested changes

2022-08-31 16:23 UTC, instanceofme commented on dataikuapi/dss/ml.py
> +
Not sure we need a dedicated method for this

2022-08-31 16:23 UTC, instanceofme commented on dataikuapi/dss/ml.py
> +        :param end_of_week_day: only useful for the week time unit. Valid values are: 1 (Sunday), 2 (Monday), ..., 7 (Saturday)
```suggestion
        :param end_of_week_day: only useful for the WEEK time unit. Valid values are: 1 (Sunday), 2 (Monday), ..., 7 (Saturday)
```

2022-08-31 16:23 UTC, instanceofme commented on dataikuapi/dss/ml.py
> +    def set_timestep_params(self, timeunit=None, n_timeunits=None, end_of_week_day=None):
If `get_timestep_params()` returns a dict, maybe this should simply be `set_timestep()`

2022-08-31 16:23 UTC, instanceofme commented on dataikuapi/dss/ml.py
> +    def set_numerical_interpolation_params(self, method=None, constant=None):
Ditto `set_numerical_interpolation()`, same for others below

2022-08-31 16:23 UTC, instanceofme commented on dataikuapi/dss/ml.py
> +    def quantiles(self):
Maybe `forecast_quantiles` to avoid ambiguity? (Ditto setter)

2022-08-31 16:23 UTC, instanceofme commented on dataikuapi/dss/ml.py
> +        :param values: List of quantiles to forecast
Should document 
- 0.5 requirement
- 0.0001-0.9999 inclusive range
- 1e-4 precision

2022-08-31 16:23 UTC, instanceofme commented on dataikuapi/dss/ml.py
> +            assert abs(quantile - math.floor(quantile * 1e4) / 1e4) > 1e-8, "Quantiles should be defined up to 4 digits after decimal point, got {}".format(quantile)
This seems like it should just be doc

2022-08-31 16:23 UTC, instanceofme commented on dataikuapi/dss/ml.py
> +        :type constant: object
Not sure I get this param
- the name?
- looks like it should be a number but the type is `object`?

(multiple instances)

2022-09-12 11:12 UTC, mhham commented on dataikuapi/apinode_client.py
> +        :return: a Python dict of the API answer. The answer contains a "results" key (which is an array of result objects)
The main difference is that input records are not aligned with output records for time series forecasting.

We could rename `records` to `past_records` to make it clear that we are using past data to forecast future data.

For the result it is the future/forecasted data, I could write this explicitly in the docstring

2022-09-12 11:51 UTC, mhham commented on dataikuapi/dss/ml.py
> +        AbstractTabularPredictionMLTaskSettings.__init__(self, client, project_key, analysis_id, mltask_id, mltask_settings)
In the same file `dataikuapi.dss.ml.AbstractTabularPredictionMLTaskSettings`

2022-09-14 13:52 UTC, instanceofme commented on dataikuapi/dss/ml.py
> +        AbstractTabularPredictionMLTaskSettings.__init__(self, client, project_key, analysis_id, mltask_id, mltask_settings)
I mean

- `AbstractTabularPredictionMLTaskSettings` does not define/override `__init__`
- IIUC (and if I look at the surrounding code), the pattern for this is supposed to be more like the below

```suggestion
        super(DSSPredictionMLTaskSettings, self).__init__(client, project_key, analysis_id, mltask_id, mltask_settings)
```

…prompting the question of why call it this way?
Granted, the former code called `DSSMLTaskSettings.__init__(self, …` but it's an oddity introduced by 4680b60 and it was seemingly not questioned when repeated here.

(ditto for the TS one)

2022-09-14 14:18 UTC, instanceofme approved these changes
Globally LGTM

2022-09-14 14:18 UTC, instanceofme commented on dataikuapi/dss/analysis.py
> +        """Creates a new prediction task in a new visual analysis lab for a dataset.
```suggestion
        """Creates a new timeseries forecasting task in this visual analysis lab for a dataset.
```

\+ should also fix the "a new visual analysis lab" → "this visual analysis lab" for clustering above

2022-09-14 14:18 UTC, instanceofme commented on dataikuapi/dss/project.py
> +        """Creates a new prediction task in a new visual analysis lab
```suggestion
        """Creates a new timeseries forecasting task in a new visual analysis lab
```

2022-09-14 14:18 UTC, instanceofme commented on dataikuapi/dss/dataset.py
> +        """Creates a new prediction task in a new visual analysis lab
```suggestion
        """Creates a new timeseries forecasting task in a new visual analysis lab
```

2022-09-14 14:18 UTC, instanceofme commented on dataikuapi/dss/ml.py
> +    def set_duplicate_timestamp_handling_method(self, method):
More future-proof if we ever add other params + more consistent with other params

```suggestion
    def set_duplicate_timestamp_handling(self, method):
```

2022-09-14 14:51 UTC, mhham commented on dataikuapi/dss/ml.py
> +        AbstractTabularPredictionMLTaskSettings.__init__(self, client, project_key, analysis_id, mltask_id, mltask_settings)
Fixed here: https://github.com/dataiku/dataiku-api-client-python/pull/260/commits/37e294de998ba68849847a25eb85c77c940a4d45

2022-09-20 12:42 UTC, mhham commented
Moving this PR to dip

2022-09-20 12:42 UTC, closed without merging